#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# Copyright 2018-2023 David Rabkin
# This script preparies ruby environment to run install.rb.
# The script uses local variables which are not POSIX but supported by most
# shells, see more:
#  https://stackoverflow.com/questions/18597697/posix-compliant-way-to-scope-variables-to-a-function-in-a-shell-script
# shellcheck disable=SC3043 # Uses local variables.
# Uses Unix shell framework shellbase:
#  https://github.com/rdavid/shellbase/

# Installs shellbase to the current shell session. Packages curl and tar are
# required.
shellbase() {
	local err pkg rel=0.9.20230606
	local src=https://github.com/rdavid/shellbase/archive/refs/tags/v$rel.tar.gz
	for pkg in curl tar; do
		command -v $pkg >/dev/null 2>&1 || {
			err=$?
			printf >&2 Install\ %s.\\n $pkg
			exit $err
		}
	done
	curl --fail --head --output /dev/null --silent $src || {
		err=$?
		printf >&2 '%s is unavailable.\n' $src
		exit $err
	}
	eval "$(
		curl --location --silent $src |
			tar --extract --gzip --to-stdout shellbase-$rel/lib/base.sh
	)"
	[ -n "${BASE_VERSION+x}" ] || {
		printf >&2 No\ shellbase.\\n
		exit 1
	}
	log shellbase "$BASE_VERSION" is installed to the current shell session.
}

# shellcheck disable=SC1091,SC2015 # File not following, A && B || C.
[ -r /usr/local/bin/base.sh ] && . /usr/local/bin/base.sh || shellbase "$@"
platform="$(uname)"
readonly \
	gems='colorize english git i18n os pidfile' \
	platform \
	pkgs=ruby

# Tests to see if a package is installed.
for p in $pkgs; do
	cmd_exists "$p" || {
		if [ "$platform" = Linux ]; then
			if [ -f /etc/arch-release ]; then
				sudo pacman --noconfirm -S "$p"
			elif [ -f /etc/redhat-release ]; then
				sudo dnf install --assumeyes "$p"
			elif [ -f /etc/debian_version ]; then
				sudo apt-get install --assume-yes "$p"
			fi
		elif [ "$platform" = Darwin ]; then
			brew install "$p"
		elif [ "$platform" = FreeBSD ]; then
			sudo pkg install "$p" devel/ruby-gems
		elif [ "$platform" = OpenBSD ]; then
			doas pkg_add install "$p"
		fi
		log "$p" is installed.
	}
done

# Installs needful Ruby packages.
for g in $gems; do
	gem list -ie "$g" >/dev/null 2>&1 || {
		if [ -f /etc/arch-release ]; then
			gem install "$g"
		else
			sudo gem install "$g"
		fi
		log "$g" is installed.
	}
done

# Runs Ruby's install.
"$(dirname "$0")"/install.rb "$@"
