// Settings:
:toc: macro
:!toc-title:
// URLs:
:img-hoc: https://hitsofcode.com/github/rdavid/dotfiles?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/dotfiles?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:img-test: https://github.com/rdavid/dotfiles/actions/workflows/test.yml/badge.svg
:url-actionlint: https://github.com/rhysd/actionlint
:url-cv: http://cv.rabkin.co.il
:url-goredo: http://www.goredo.cypherpunks.su/Install.html
:url-hoc: https://hitsofcode.com/view/github/rdavid/dotfiles?branch=master
:url-license: https://github.com/rdavid/dotfiles/blob/master/LICENSES/0BSD.txt
:url-redo: http://cr.yp.to/redo.html
:url-shellcheck: https://github.com/koalaman/shellcheck
:url-shfmt: https://github.com/mvdan/sh
:url-test: https://github.com/rdavid/dotfiles/actions/workflows/test.yml
:url-typos: https://github.com/crate-ci/typos
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint

= Dotfiles

// The width is set to 72 characters, and the height is 7 lines. An ASCII art
// generator is used with the specific font Roman:
//  http://patorjk.com/software/taag/#p=display&f=Roman&t=dotfiles
[,sh]
----
          .o8                .    .o88o.  o8o  oooo                     
         "888              .o8    888 `"  `"'  `888                     
     .oooo888   .ooooo.  .o888oo o888oo  oooo   888   .ooooo.   .oooo.o 
    d88' `888  d88' `88b   888    888    `888   888  d88' `88b d88(  "8 
    888   888  888   888   888    888     888   888  888ooo888 `"Y88b.  
    888   888  888   888   888 .  888     888   888  888    .o o.  )88b 
    `Y8bod88P" `Y8bod8P'   "888" o888o   o888o o888o `Y8bod8P' 8""888P' 
----

image:{img-test}[test,link={url-test}]
image:{img-hoc}[hits of code,link={url-hoc}]
image:{img-license}[license,link={url-license}]

toc::[]

== About

Hi, I'm http://cv.rabkin.co.il[David Rabkin].
These are my dotfiles.

== Installation

[,sh]
----
git clone https://github.com/rdavid/dotfiles.git ~/dotfiles &&
  cd ~/dotfiles &&
  ./install
----

== Test

The project uses Daniel J. Bernstein's build system {url-redo}[`redo`].
You can install Sergey Matveev's {url-goredo}[`goredo`] implementation.
`redo lint` applies the following linters to the source files:
{url-actionlint}[`actionlint`],
{url-shellcheck}[`shellcheck`],
{url-shfmt}[`shfmt`],
{url-typos}[`typos`],
{url-vale}[`vale`],
{url-yamllint}[`yamllint`].

== License

`dotfiles` is copyright {url-cv}[David Rabkin] and available under a
{url-license}[Zero-Clause BSD license].
