// Settings:
:toc: macro
:!toc-title:
// URLs:
:img-hoc: https://hitsofcode.com/github/rdavid/dotfiles?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/dotfiles?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:img-test: https://github.com/rdavid/dotfiles/actions/workflows/test.yml/badge.svg
:url-actionlint: https://github.com/rhysd/actionlint
:url-conform: https://github.com/siderolabs/conform
:url-cv: http://cv.rabkin.co.il
:url-goredo: http://www.goredo.stargrave.org/INSTALL.html
:url-hoc: https://hitsofcode.com/view/github/rdavid/dotfiles?branch=master
:url-install: https://github.com/rdavid/dotfiles/blob/master/install
:url-license: https://github.com/rdavid/dotfiles/blob/master/LICENSES/0BSD.txt
:url-redo: http://cr.yp.to/redo.html
:url-shellcheck: https://github.com/koalaman/shellcheck
:url-shfmt: https://github.com/mvdan/sh
:url-test: https://github.com/rdavid/dotfiles/actions/workflows/test.yml
:url-typos: https://github.com/crate-ci/typos
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint

= Dotfiles

// The width is set to 78 characters, and the height is 7 lines. An ASCII art
// generator is used with the specific font Roman:
//  http://patorjk.com/software/taag/#p=display&f=Roman&t=++dotfiles
[,sh]
----
                .o8                .    .o88o.  o8o  oooo                     
               "888              .o8    888 `"  `"'  `888                     
           .oooo888   .ooooo.  .o888oo o888oo  oooo   888   .ooooo.   .oooo.o 
          d88' `888  d88' `88b   888    888    `888   888  d88' `88b d88(  "8 
          888   888  888   888   888    888     888   888  888ooo888 `"Y88b.  
          888   888  888   888   888 .  888     888   888  888    .o o.  )88b 
          `Y8bod88P" `Y8bod8P'   "888" o888o   o888o o888o `Y8bod8P' 8""888P' 
----

[subs=attributes+]
++++
<div align="right">
<a href="{url-test}"><img src="{img-test}" alt="test"></a>
<a href="{url-hoc}"><img src="{img-hoc}" alt="hits of code"></a>
<a href="{url-license}"><img src="{img-license}" alt="license"></a>
</div>
++++

toc::[]

ifdef::pages-build[]
++++
<div id="repo-link">
  <a href="https://github.com/rdavid/dotfiles" aria-label="GitHub repository" target="_blank" rel="noopener">
    <svg viewBox="0 0 16 16" width="18" height="18" fill="currentColor" aria-hidden="true">
      <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8Z"/>
    </svg>
  </a>
</div>
++++
endif::[]

== About

{url-cv}[David Rabkin] maintains this repository of personal dotfiles.
It holds settings for the shell, Git, tmux, and other everyday tools, plus
an installer that sets them all up.

== Installation

Clone the repository and run the {url-install}[installer]:

[,sh]
----
git clone https://github.com/rdavid/dotfiles.git ~/dotfiles &&
  cd ~/dotfiles &&
  ./install
----

== Test

The project builds with Daniel J. Bernstein's {url-redo}[`redo`].
Sergey Matveev's {url-goredo}[`goredo`] offers a compatible implementation.
`redo lint` runs these linters:
{url-actionlint}[`actionlint`],
{url-conform}[`conform`],
{url-shellcheck}[`shellcheck`],
{url-shfmt}[`shfmt`],
{url-typos}[`typos`],
{url-vale}[`vale`], and
{url-yamllint}[`yamllint`].

== License

{url-cv}[David Rabkin] holds the copyright and releases `dotfiles` under the
{url-license}[Zero-Clause BSD license].

ifdef::pages-build[]
++++
<footer id="site-footer">
  <div class="footer-left">
    <img src="favicon.svg" alt="" width="20" height="20">
    <span>dotfiles by <a href="http://cv.rabkin.co.il" target="_blank" rel="noopener">David Rabkin</a></span>
  </div>
  <div class="footer-links">
    <a href="https://github.com/rdavid/dotfiles" target="_blank" rel="noopener">GitHub</a>
    <a href="https://github.com/rdavid/dotfiles/blob/master/LICENSES/0BSD.txt" target="_blank" rel="noopener">0BSD License</a>
  </div>
</footer>
++++
endif::[]
